// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SipUIClient is the client API for SipUI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SipUIClient interface {
	// ListEngineSpecs returns a list of Message Engine(s) that can be started through the UI.
	ListEngineSpecs(ctx context.Context, in *ListEngineSpecsRequest, opts ...grpc.CallOption) (SipUI_ListEngineSpecsClient, error)
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error)
}

type sipUIClient struct {
	cc grpc.ClientConnInterface
}

func NewSipUIClient(cc grpc.ClientConnInterface) SipUIClient {
	return &sipUIClient{cc}
}

func (c *sipUIClient) ListEngineSpecs(ctx context.Context, in *ListEngineSpecsRequest, opts ...grpc.CallOption) (SipUI_ListEngineSpecsClient, error) {
	stream, err := c.cc.NewStream(ctx, &SipUI_ServiceDesc.Streams[0], "/v1.SipUI/ListEngineSpecs", opts...)
	if err != nil {
		return nil, err
	}
	x := &sipUIListEngineSpecsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type SipUI_ListEngineSpecsClient interface {
	Recv() (*ListEngineSpecsResponse, error)
	grpc.ClientStream
}

type sipUIListEngineSpecsClient struct {
	grpc.ClientStream
}

func (x *sipUIListEngineSpecsClient) Recv() (*ListEngineSpecsResponse, error) {
	m := new(ListEngineSpecsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *sipUIClient) IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error) {
	out := new(IsReadOnlyResponse)
	err := c.cc.Invoke(ctx, "/v1.SipUI/IsReadOnly", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SipUIServer is the server API for SipUI service.
// All implementations must embed UnimplementedSipUIServer
// for forward compatibility
type SipUIServer interface {
	// ListEngineSpecs returns a list of Message Engine(s) that can be started through the UI.
	ListEngineSpecs(*ListEngineSpecsRequest, SipUI_ListEngineSpecsServer) error
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error)
	mustEmbedUnimplementedSipUIServer()
}

// UnimplementedSipUIServer must be embedded to have forward compatible implementations.
type UnimplementedSipUIServer struct {
}

func (UnimplementedSipUIServer) ListEngineSpecs(*ListEngineSpecsRequest, SipUI_ListEngineSpecsServer) error {
	return status.Errorf(codes.Unimplemented, "method ListEngineSpecs not implemented")
}
func (UnimplementedSipUIServer) IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsReadOnly not implemented")
}
func (UnimplementedSipUIServer) mustEmbedUnimplementedSipUIServer() {}

// UnsafeSipUIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SipUIServer will
// result in compilation errors.
type UnsafeSipUIServer interface {
	mustEmbedUnimplementedSipUIServer()
}

func RegisterSipUIServer(s grpc.ServiceRegistrar, srv SipUIServer) {
	s.RegisterService(&SipUI_ServiceDesc, srv)
}

func _SipUI_ListEngineSpecs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListEngineSpecsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SipUIServer).ListEngineSpecs(m, &sipUIListEngineSpecsServer{stream})
}

type SipUI_ListEngineSpecsServer interface {
	Send(*ListEngineSpecsResponse) error
	grpc.ServerStream
}

type sipUIListEngineSpecsServer struct {
	grpc.ServerStream
}

func (x *sipUIListEngineSpecsServer) Send(m *ListEngineSpecsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _SipUI_IsReadOnly_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsReadOnlyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SipUIServer).IsReadOnly(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.SipUI/IsReadOnly",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SipUIServer).IsReadOnly(ctx, req.(*IsReadOnlyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SipUI_ServiceDesc is the grpc.ServiceDesc for SipUI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SipUI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.SipUI",
	HandlerType: (*SipUIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IsReadOnly",
			Handler:    _SipUI_IsReadOnly_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListEngineSpecs",
			Handler:       _SipUI_ListEngineSpecs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "sip-ui.proto",
}
